---
version: 2
updates:
- package-ecosystem: "cargo"
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 1
  reviewers:
  - markmcdowell
  versioning-strategy: increase
  commit-message:
    prefix: chore
    include: scope
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
  commit-message:
    prefix: build
    include: scope
