[package]
name = "reactive-redis"
version = "0.3.0"
authors = ["Mark McDowell <mark.mcdowell@reactivemarkets.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
redis-module = { version="0.26.0", features = ["experimental-api", "test"]}
