[package]
name = "toolbox-redis"
version = "0.1.0"
authors = ["Mark McDowell <mark.mcdowell@reactivemarkets.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
redis-module = { version="0.7.0", features = ["experimental-api"]}
