---
name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v5
      - run: rustup update stable
      - run: rustup default stable
      - run: cargo build --release --all-features
      - uses: actions/upload-artifact@v4
        with:
          name: reactive_redis
          path: target/release/libreactive_redis.so
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v5
      - run: rustup update stable
      - run: rustup default stable
      - run: rustup component add clippy
      - run: cargo clippy
