---
name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ci:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/cargo@v1.0.3
        with:
          command: build
          args: --release --all-features
      - uses: actions/upload-artifact@v4
        with:
          name: reactive_redis
          path: target/release/libreactive_redis.so
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - run: cargo clippy
