---
name: CI

on: [push, pull_request]

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - uses: actions/upload-artifact@v1
        with:
          name: reactive_redis
          path: target/release/libreactive_redis.so
