---
name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions-rs/cargo@v1.0.3
        with:
          command: build
          args: --release --all-features
      - uses: actions/upload-artifact@v2.2.4
        with:
          name: reactive_redis
          path: target/release/libreactive_redis.so
